version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./app-data:/app-data  # Зберігаємо дані з бази даних поза контейнером
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db  # Зберігаємо дані MongoDB поза контейнером
